"""
agents/agents/coordinator_agent.py
CoordinatorAgent: Orchestrates all domain agents, synthesizes the final risk assessment,
generates LLM explanation, and dispatches alerts.
"""

import asyncio
import json
import logging
from typing import Any, Optional

import httpx

from ..core.base_agent import BaseAgent
from ..core.redis_bus import CHANNELS
from .weather_agent import WeatherAgent
from .ocean_agent import OceanAgent
from .vessel_agent import VesselAgent
from .ecosystem_agent import EcosystemAgent
from .disaster_reasoning_agent import DisasterReasoningAgent, RiskAssessment
from ..core.config import config

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../../../"))
from shared.orca_event import OrcaEvent
from shared.severity import AlertLevel

logger = logging.getLogger(__name__)


EXPLANATION_TEMPLATE = """
🌊 ORCA Marine Risk Assessment
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Risk Level: {alert_level}
Disaster Type: {disaster_type}
Probability: {probability:.0%} | Confidence: {confidence:.0%}

📊 Key Indicators:
{indicators}

⚠️ Recommended Actions:
{actions}

📡 Data Sources: Weather Agent, Ocean Agent, Vessel Agent, Ecosystem Agent
🤖 Generated by ORCA Coordinator | {timestamp}
""".strip()


class CoordinatorAgent(BaseAgent):
    """
    The brain of ORCA.
    1. Dispatches all 5 domain agents concurrently
    2. Passes results to DisasterReasoningAgent
    3. Generates LLM explanation (or template fallback)
    4. Checks alert threshold → dispatches to backend Alert Service
    5. Updates Redis with current risk zones for VesselAgent
    """

    def __init__(self, redis_url: str, backend_url: str = "http://backend:8000"):
        super().__init__(
            agent_id="coordinator_agent",
            display_name="Coordinator Agent",
            redis_url=redis_url,
        )
        self.backend_url = backend_url

        # Initialize all domain agents
        self.weather_agent = WeatherAgent(redis_url)
        self.ocean_agent = OceanAgent(redis_url)
        self.vessel_agent = VesselAgent(redis_url, config.aishub_username)
        self.ecosystem_agent = EcosystemAgent(redis_url)
        self.reasoning_agent = DisasterReasoningAgent(redis_url)

    # ── BaseAgent abstract implementations ───────────────────────────────

    async def fetch_data(self) -> Any:
        return None

    def process_data(self, raw: Any) -> dict:
        return {}

    def calculate_risk_score(self, observations: dict) -> float:
        return 0.0

    async def run(self) -> OrcaEvent:
        return await self.orchestrate()

    # ── Main orchestration ────────────────────────────────────────────────

    async def orchestrate(self) -> OrcaEvent:
        """
        Full ORCA cycle:
        Dispatch agents → Reason → Explain → Check threshold → Alert
        """
        logger.info("=== ORCA Coordinator: Starting agent cycle ===")

        # Step 1: Run all domain agents in parallel
        domain_events = await self._dispatch_domain_agents()

        # Step 2: Extract observations from each event
        weather_obs = domain_events["weather"].observations
        ocean_obs = domain_events["ocean"].observations
        satellite_obs = domain_events.get("satellite", OrcaEvent("satellite_agent")).observations
        vessel_obs = domain_events["vessel"].observations
        ecosystem_obs = domain_events["ecosystem"].observations

        # Cache SST for EcosystemAgent next run
        max_sst = ocean_obs.get("max_sst_celsius", 28.5)
        await self.cache_set("ocean:latest_max_sst", str(max_sst), ttl_seconds=1800)

        # Step 3: Disaster reasoning
        assessment: RiskAssessment = self.reasoning_agent.reason(
            weather_obs, ocean_obs, satellite_obs, vessel_obs, ecosystem_obs
        )
        logger.info(
            f"Risk assessment: {assessment.disaster_type.value} "
            f"| P={assessment.probability:.2f} | {assessment.alert_level.value}"
        )

        # Step 4: Generate explanation
        explanation = await self._generate_explanation(assessment, domain_events)

        # Step 5: Build final event
        final_event = OrcaEvent(
            agent_id=self.agent_id,
            observations={
                "assessment": assessment.to_dict(),
                "explanation": explanation,
                "domain_risk_scores": {
                    "weather": domain_events["weather"].risk_score,
                    "ocean": domain_events["ocean"].risk_score,
                    "vessel": domain_events["vessel"].risk_score,
                    "ecosystem": domain_events["ecosystem"].risk_score,
                },
            },
            risk_score=assessment.probability,
            confidence=assessment.confidence,
            data_source="coordinator_synthesis",
        )

        # Step 6: Check threshold and dispatch alert
        if (
            assessment.probability >= config.alert_threshold_probability
            and assessment.confidence >= config.alert_threshold_confidence
            and assessment.alert_level != AlertLevel.GREEN
        ):
            await self._dispatch_alert(assessment, explanation)

        # Step 7: Update risk zones in Redis (for VesselAgent)
        await self._update_risk_zones(assessment)

        # Step 8: Publish final event for dashboard WebSocket
        await self.publish(final_event, channel=CHANNELS["final"])

        logger.info("=== ORCA Coordinator: Cycle complete ===")
        return final_event

    # ── Helpers ───────────────────────────────────────────────────────────

    async def _dispatch_domain_agents(self) -> dict[str, OrcaEvent]:
        """Run all 5 domain agents concurrently and collect results."""
        results = await asyncio.gather(
            self.weather_agent.execute(),
            self.ocean_agent.execute(),
            self.vessel_agent.execute(),
            self.ecosystem_agent.execute(),
            return_exceptions=True,
        )

        agents = ["weather", "ocean", "vessel", "ecosystem"]
        domain_events = {}
        for name, result in zip(agents, results):
            if isinstance(result, Exception):
                logger.error(f"{name} agent raised exception: {result}")
                domain_events[name] = OrcaEvent.error_event(f"{name}_agent", str(result))
            elif isinstance(result, OrcaEvent):
                domain_events[name] = result
            else:
                domain_events[name] = OrcaEvent.error_event(f"{name}_agent", "No event returned")

        return domain_events

    async def _generate_explanation(
        self, assessment: RiskAssessment, domain_events: dict[str, OrcaEvent]
    ) -> str:
        """
        Generate plain-language explanation.
        Tries LLM first; falls back to template if LLM unavailable.
        """
        if config.google_api_key and not config.fallback_to_template:
            try:
                return await self._llm_explain(assessment, domain_events)
            except Exception as exc:
                logger.warning(f"LLM explanation failed: {exc} — using template")

        return self._template_explain(assessment)

    async def _llm_explain(
        self, assessment: RiskAssessment, domain_events: dict
    ) -> str:
        """Call Google Gemini to generate natural language explanation."""
        from langchain_google_genai import ChatGoogleGenerativeAI
        from langchain_core.messages import HumanMessage

        llm = ChatGoogleGenerativeAI(
            model=config.llm_model,
            google_api_key=config.google_api_key,
            temperature=0.3,
        )

        prompt = f"""
You are ORCA, a marine disaster management AI assistant.
A risk assessment has been completed. Write a clear, professional alert explanation
in 3-4 sentences for disaster management authorities.

Assessment:
- Disaster Type: {assessment.disaster_type.value}
- Probability: {assessment.probability:.0%}
- Alert Level: {assessment.alert_level.value}
- Key Indicators: {', '.join(assessment.primary_indicators[:3])}

Write the explanation in plain English. Be specific about the risk.
Do not use bullet points. Write as continuous prose.
End with the most urgent recommended action.
""".strip()

        response = await llm.ainvoke([HumanMessage(content=prompt)])
        return response.content

    def _template_explain(self, assessment: RiskAssessment) -> str:
        """Fallback template-based explanation (no LLM required)."""
        from datetime import datetime, timezone
        indicators_text = "\n".join(
            f"  • {ind}" for ind in assessment.primary_indicators[:4]
        ) or "  • No critical indicators detected"

        actions_text = "\n".join(
            f"  {i+1}. {act}"
            for i, act in enumerate(assessment.preliminary_actions[:3])
        )

        return EXPLANATION_TEMPLATE.format(
            alert_level=assessment.alert_level.value,
            disaster_type=assessment.disaster_type.value.replace("_", " ").title(),
            probability=assessment.probability,
            confidence=assessment.confidence,
            indicators=indicators_text,
            actions=actions_text,
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
        )

    async def _dispatch_alert(
        self, assessment: RiskAssessment, explanation: str
    ) -> None:
        """POST the alert to the backend Alert Service."""
        payload = {
            "alert_level": assessment.alert_level.value,
            "alert_type": assessment.disaster_type.value,
            "title": f"{assessment.disaster_type.value.replace('_', ' ').title()} Warning — ORCA Alert",
            "explanation": explanation,
            "recommended_actions": assessment.preliminary_actions,
            "confidence": assessment.confidence,
            "source_agents": assessment.contributing_agents,
            "metadata": assessment.raw_scores,
        }
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                resp = await client.post(
                    f"{self.backend_url}/api/v1/alerts/internal",
                    json=payload,
                    headers={"X-Internal-Key": "orca-internal-secret"},
                )
                resp.raise_for_status()
                logger.info(f"Alert dispatched: {resp.json().get('alert_id')}")
        except Exception as exc:
            logger.error(f"Failed to dispatch alert to backend: {exc}")

    async def _update_risk_zones(self, assessment: RiskAssessment) -> None:
        """Cache current risk zones for VesselAgent to use."""
        if assessment.alert_level == AlertLevel.GREEN:
            await self.cache_set("alerts:active:zones", "[]", ttl_seconds=900)
            return

        # Simplified: flag primary Indian Ocean as risk zone
        zones = [{"id": "current", "center_lat": 15.0, "center_lon": 80.0, "radius_km": 300}]
        await self.cache_set(
            "alerts:active:zones", json.dumps(zones), ttl_seconds=900
        )
